server:
  port: 8009
  servlet:
    #访问根路径
    context-path: /order
spring:
  application:
    #服务名
    name: leonMall-order
#eureka配置
eureka:
  client:
    #是否将自己注册到eureka，默认为true
    register-with-eureka: true
    #是否从EurekaServer中抓取已有的注册信息，默认为true，单点无所谓，集群必须设置true才能和ribbon使用负载均衡
    fetch-registry: true
    #eureka注册中心地址
    service-url:
      defaultZone: http://eureka.com:7001/eureka,http://eureka.com:7002/eureka

#支付服务url
paymentServerHost: http://LEONMALL-PAYMENT