server:
  #服务端口
  port: 8007
  servlet:
    #访问根路径
    context-path: /payment
#spring相关配置
spring:
  application:
    #服务名
    name: leonMall-payment
  datasource:
    #当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    #数据库驱动包
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysql?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: leonChen@1016
#mybatis:配置
mybatis:
  mapperLocations: classpath:dao/*.xml
  #所有pojo别名类所在包
  type-aliases-package: org.leon.pojo
#eureka配置
eureka:
  client:
    #表示是否将自己注册进eureka  默认为true
    register-with-eureka: true
    #是否从EurekaServer中抓取已有的注册信息，默认为true，单点无所谓，集群必须设置true才能和ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #与eureka server交互的地址，注册服务时需要这个地址
      defaultZone: http://eureka.com:7001/eureka,http://eureka.com:7002/eureka